language: node_js
node_js:
- '16.0'
script:
- npm test
- npm run coverage
after_success:
- curl -Os https://uploader.codecov.io/latest/linux/codecov
- chmod +x codecov
- ./codecov -t c50d2b94-561a-4c13-beaf-6a96d3c4055e